In [45]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [46]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape(-1,1)
y = np.array([5, 20, 14, 32, 22, 38])

In [47]:
model = LinearRegression()

In [48]:
model.fit(x, y)

LinearRegression()

In [49]:
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.7158756137479542


In [50]:
print(f"intercept: {model.intercept_}")


print(f"slope: {model.coef_}")

intercept: 5.633333333333329
slope: [0.54]


In [51]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print(f"intercept: {new_model.intercept_}")


print(f"slope: {new_model.coef_}")

intercept: [5.63333333]
slope: [[0.54]]


In [52]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [53]:
y_pred = model.intercept_ + model.coef_ * x
print(f"predicted response:\n{y_pred}")

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [54]:
x_new = np.arange(5).reshape((-1, 1))
x_new

y_new = model.predict(x_new)
y_new

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

--------------------------------------------------------------------------------------------------

# multiple liner regression

In [55]:
import numpy as np
from sklearn.linear_model import LinearRegression

x = [
  [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]
]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [56]:
model = LinearRegression().fit(x, y)

In [57]:
r_sq = model.score(x, y)
print(f"coefficient {r_sq}") 
print(f"intercept: {model.intercept_}")
print(f"coefficients: {model.coef_}")


coefficient 0.8615939258756776
intercept: 5.522579275198183
coefficients: [0.44706965 0.25502548]


In [58]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [59]:
y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [60]:
x_new = np.arange(10).reshape((-1, 2))
x_new

y_new = model.predict(x_new)
y_new

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])

--------------------------------------------------------------

# Polynomial Regression

In [61]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [62]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [63]:
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [64]:
transformer.fit(x)

PolynomialFeatures(include_bias=False)

In [65]:
x_ = transformer.transform(x)

In [66]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [67]:
model = LinearRegression().fit(x_, y)

In [68]:
r_sq = model.score(x_, y)
print(f"coefficient of determination: {r_sq}")


print(f"intercept: {model.intercept_}")


print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8908516262498563
intercept: 21.372321428571453
coefficients: [-1.32357143  0.02839286]


In [69]:
x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)

In [70]:
model = LinearRegression(fit_intercept=False).fit(x_, y)

In [71]:
r_sq = model.score(x_, y)
print(f"coefficient of determination: {r_sq}")


print(f"intercept: {model.intercept_}")


print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8908516262498563
intercept: 0.0
coefficients: [21.37232143 -1.32357143  0.02839286]


In [72]:
y_pred = model.predict(x_)
print(f"predicted response:\n{y_pred}")

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]
